import { NextRequest, NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb, PDFPage, PDFFont } from "pdf-lib";
import { Hospital } from "@/types/hospital";
import hospitalsData from "@/data/hospitals.json";

const hospitals = hospitalsData as unknown as Hospital[];

interface HouseholdMember {
  name: string;
  dob: string;
  relationship: string;
  medicalRecord: string;
}

interface KaiserWaBody {
  hospital_id: string;
  patientName: string;
  medicalRecordNumber?: string;
  dateOfBirth?: string;
  ssn?: string;
  noSsn?: boolean;
  streetAddress?: string;
  city?: string;
  state?: string;
  zipCode?: string;
  isUnhoused?: string;
  phoneNumber?: string;
  phoneType?: string;
  enrolledStateAssistance?: string;
  householdSize?: string;
  monthlyIncome?: string;
  incomeTypes?: Record<string, boolean>;
  zeroIncomeExplanation?: string;
  healthCareCosts?: string;
  members?: HouseholdMember[];
  contactMe?: boolean;
  optOutCreditCheck?: boolean;
}

function formatDate(dateStr: string): string {
  if (!dateStr) return "";
  const d = new Date(dateStr + "T00:00:00");
  if (isNaN(d.getTime())) return dateStr;
  return `${(d.getMonth() + 1).toString().padStart(2, "0")}/${d.getDate().toString().padStart(2, "0")}/${d.getFullYear()}`;
}

const NAVY = rgb(15 / 255, 23 / 255, 42 / 255);
const GRAY = rgb(100 / 255, 116 / 255, 139 / 255);
const LIGHT_GRAY = rgb(226 / 255, 232 / 255, 240 / 255);
const TEAL = rgb(13 / 255, 148 / 255, 136 / 255);
const CHECK = "X";

// PDF drawing helpers
function drawLabel(page: PDFPage, x: number, y: number, text: string, font: PDFFont, size = 8) {
  page.drawText(text, { x, y, size, font, color: GRAY });
}

function drawValue(page: PDFPage, x: number, y: number, text: string, font: PDFFont, size = 10) {
  page.drawText(text || "", { x, y, size, font, color: NAVY });
}

function drawFieldBox(page: PDFPage, x: number, y: number, w: number, h: number) {
  page.drawRectangle({ x, y, width: w, height: h, borderColor: LIGHT_GRAY, borderWidth: 0.5, color: rgb(1, 1, 1) });
}

function drawSectionHeader(page: PDFPage, x: number, y: number, text: string, font: PDFFont, width: number) {
  page.drawRectangle({ x, y: y - 4, width, height: 22, color: rgb(241 / 255, 245 / 255, 249 / 255) });
  page.drawText(text, { x: x + 8, y: y + 2, size: 11, font, color: NAVY });
  return y - 30;
}

function drawCheckItem(page: PDFPage, x: number, y: number, label: string, checked: boolean, font: PDFFont, boldFont: PDFFont) {
  page.drawRectangle({ x, y: y - 2, width: 10, height: 10, borderColor: GRAY, borderWidth: 0.5 });
  if (checked) {
    page.drawText(CHECK, { x: x + 1.5, y: y - 0.5, size: 9, font: boldFont, color: TEAL });
  }
  page.drawText(label, { x: x + 15, y, size: 8, font, color: NAVY });
}

async function generateKaiserWaPdf(body: KaiserWaBody): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const W = 612;
  const H = 792;
  const M = 40; // margin
  const CW = W - 2 * M; // content width

  // === PAGE 1 ===
  const p1 = pdfDoc.addPage([W, H]);
  let y = H - 40;

  // Header
  p1.drawText("KAISER PERMANENTE", { x: M, y, size: 12, font: fontBold, color: NAVY });
  p1.drawText("Washington", { x: M + font.widthOfTextAtSize("KAISER PERMANENTE  ", 12), y, size: 12, font, color: GRAY });
  y -= 6;
  p1.drawLine({ start: { x: M, y }, end: { x: W - M, y }, thickness: 2, color: TEAL });
  y -= 22;

  p1.drawText("Medical Financial Assistance (MFA) Program Application", { x: M, y, size: 14, font: fontBold, color: NAVY });
  y -= 14;
  p1.drawText("Generated by Civis Health", { x: M, y, size: 8, font, color: GRAY });
  y -= 24;

  // Section 1: Patient Information
  y = drawSectionHeader(p1, M, y, "Section 1: Patient Information", fontBold, CW);
  y -= 4;

  // Row: Name + MRN
  drawLabel(p1, M, y + 12, "NAME", font);
  drawFieldBox(p1, M, y - 4, CW * 0.65 - 5, 16);
  drawValue(p1, M + 4, y, body.patientName, font);

  const mrnX = M + CW * 0.65 + 5;
  drawLabel(p1, mrnX, y + 12, "MEDICAL RECORD NUMBER (OPTIONAL)", font);
  drawFieldBox(p1, mrnX, y - 4, CW * 0.35 - 5, 16);
  drawValue(p1, mrnX + 4, y, body.medicalRecordNumber ?? "", font);
  y -= 28;

  // Row: DOB + SSN
  drawLabel(p1, M, y + 12, "DATE OF BIRTH", font);
  drawFieldBox(p1, M, y - 4, CW * 0.35 - 5, 16);
  drawValue(p1, M + 4, y, formatDate(body.dateOfBirth ?? ""), font);

  const ssnX = M + CW * 0.35 + 5;
  drawLabel(p1, ssnX, y + 12, "SOCIAL SECURITY NUMBER (OPTIONAL)", font);
  drawFieldBox(p1, ssnX, y - 4, CW * 0.35 - 5, 16);
  drawValue(p1, ssnX + 4, y, body.noSsn ? "" : (body.ssn ?? ""), font);

  const noSsnX = M + CW * 0.7 + 10;
  drawCheckItem(p1, noSsnX, y, "I do not have a SSN", body.noSsn ?? false, font, fontBold);
  y -= 28;

  // Row: Address
  drawLabel(p1, M, y + 12, "MAILING ADDRESS (STREET)", font);
  drawFieldBox(p1, M, y - 4, CW, 16);
  drawValue(p1, M + 4, y, body.streetAddress ?? "", font);
  y -= 28;

  // Row: City + State + Zip
  drawLabel(p1, M, y + 12, "CITY", font);
  drawFieldBox(p1, M, y - 4, CW * 0.5 - 5, 16);
  drawValue(p1, M + 4, y, body.city ?? "", font);

  const stX = M + CW * 0.5 + 5;
  drawLabel(p1, stX, y + 12, "STATE", font);
  drawFieldBox(p1, stX, y - 4, CW * 0.2 - 5, 16);
  drawValue(p1, stX + 4, y, body.state ?? "", font);

  const zipX = M + CW * 0.7 + 5;
  drawLabel(p1, zipX, y + 12, "ZIP CODE", font);
  drawFieldBox(p1, zipX, y - 4, CW * 0.3 - 5, 16);
  drawValue(p1, zipX + 4, y, body.zipCode ?? "", font);
  y -= 28;

  // Row: Unhoused + Phone
  drawLabel(p1, M, y + 12, "IS PATIENT CURRENTLY UNHOUSED?", font);
  drawCheckItem(p1, M, y - 4, "Yes", body.isUnhoused === "Yes", font, fontBold);
  drawCheckItem(p1, M + 50, y - 4, "No", body.isUnhoused === "No", font, fontBold);

  const phX = M + CW * 0.4;
  drawLabel(p1, phX, y + 12, "PRIMARY PHONE NUMBER", font);
  drawFieldBox(p1, phX, y - 4, CW * 0.35, 16);
  drawValue(p1, phX + 4, y, body.phoneNumber ?? "", font);

  const ptX = M + CW * 0.78;
  (["Home", "Mobile", "Work", "Other"] as const).forEach((opt, i) => {
    drawCheckItem(p1, ptX, y + 4 - i * 12, opt, body.phoneType === opt, font, fontBold);
  });
  y -= 44;

  // Row: State assistance
  drawLabel(p1, M, y + 12, "IS THE PATIENT ENROLLED IN A STATE-BASED ASSISTANCE PROGRAM (SNAP, TANF, WIC, MEDICAID)?", font, 7);
  y -= 4;
  drawCheckItem(p1, M, y, "Yes", body.enrolledStateAssistance === "Yes", font, fontBold);
  drawCheckItem(p1, M + 50, y, "No", body.enrolledStateAssistance === "No", font, fontBold);
  y -= 24;

  // Section 2: Household Information
  y = drawSectionHeader(p1, M, y, "Section 2: Household Information", fontBold, CW);
  y -= 4;

  // Household size + Income
  drawLabel(p1, M, y + 12, "HOUSEHOLD SIZE", font);
  drawFieldBox(p1, M, y - 4, 80, 16);
  drawValue(p1, M + 4, y, body.householdSize ?? "", font);

  const incX = M + 120;
  drawLabel(p1, incX, y + 12, "MONTHLY GROSS HOUSEHOLD INCOME", font);
  drawFieldBox(p1, incX, y - 4, 140, 16);
  drawValue(p1, incX + 4, y, body.monthlyIncome ? `$${body.monthlyIncome}` : "", font);
  y -= 30;

  // Income types
  drawLabel(p1, M, y + 4, "HOUSEHOLD INCOME TYPES (CHECK ALL THAT APPLY):", font);
  y -= 10;

  const incomeLabels: [string, string][] = [
    ["incomeBusiness", "Business/rental income"],
    ["incomeEmployment", "Employment income/wages"],
    ["incomeVeterans", "Veterans benefits income"],
    ["incomeInterest", "Interest or dividends income"],
    ["incomeSelfEmployed", "Self-employed income"],
    ["incomeSocialSecurity", "Social Security/supplemental security income"],
    ["incomeUnemployment", "Unemployment benefits/disability income"],
    ["incomeSpousalChild", "Spousal/child support payments received"],
    ["incomePension", "Received pension/retirement/annuities income"],
    ["incomeNone", "No household income in the past 2 months"],
  ];

  const colW = CW / 2;
  for (let i = 0; i < incomeLabels.length; i++) {
    const [key, label] = incomeLabels[i];
    const col = i % 2;
    const colX = M + col * colW;
    drawCheckItem(p1, colX, y, label, !!(body.incomeTypes?.[key]), font, fontBold);
    if (col === 1 || i === incomeLabels.length - 1) y -= 14;
  }
  y -= 14;

  // Zero income explanation
  if (body.incomeTypes?.incomeNone && body.zeroIncomeExplanation) {
    drawLabel(p1, M, y + 12, "ZERO INCOME EXPLANATION:", font);
    drawFieldBox(p1, M, y - 30, CW, 40);
    // Word-wrap the explanation
    const words = body.zeroIncomeExplanation.split(" ");
    let line = "";
    let ly = y - 4;
    for (const word of words) {
      const test = line ? `${line} ${word}` : word;
      if (font.widthOfTextAtSize(test, 8) > CW - 12) {
        p1.drawText(line, { x: M + 4, y: ly, size: 8, font, color: NAVY });
        ly -= 10;
        line = word;
      } else {
        line = test;
      }
    }
    if (line) p1.drawText(line, { x: M + 4, y: ly, size: 8, font, color: NAVY });
    y -= 48;
  }

  // Health care costs
  drawLabel(p1, M, y + 12, "12-MONTH OUT-OF-POCKET HEALTH CARE COSTS", font);
  drawFieldBox(p1, M, y - 4, 200, 16);
  drawValue(p1, M + 4, y, body.healthCareCosts ? `$${body.healthCareCosts}` : "", font);

  // === PAGE 2 ===
  const p2 = pdfDoc.addPage([W, H]);
  y = H - 40;

  // Header
  p2.drawText("KAISER PERMANENTE", { x: M, y, size: 12, font: fontBold, color: NAVY });
  p2.drawText("MFA Application - Page 2", { x: W - M - font.widthOfTextAtSize("MFA Application - Page 2", 9), y, size: 9, font, color: GRAY });
  y -= 6;
  p2.drawLine({ start: { x: M, y }, end: { x: W - M, y }, thickness: 1, color: TEAL });
  y -= 24;

  // Household members table
  y = drawSectionHeader(p2, M, y, "Household Members Applying for MFA", fontBold, CW);
  y -= 4;

  // Table headers
  const cols = [
    { label: "Name", w: CW * 0.35 },
    { label: "Date of Birth", w: CW * 0.2 },
    { label: "Relationship", w: CW * 0.25 },
    { label: "Medical Record #", w: CW * 0.2 },
  ];
  let colStartX = M;
  for (const col of cols) {
    drawLabel(p2, colStartX + 4, y, col.label, fontBold, 8);
    colStartX += col.w;
  }
  y -= 14;

  // Table rows
  const members = body.members ?? [];
  for (let i = 0; i < 5; i++) {
    const m = members[i];
    colStartX = M;
    for (let c = 0; c < cols.length; c++) {
      drawFieldBox(p2, colStartX, y - 4, cols[c].w - 4, 16);
      if (m) {
        const vals = [m.name, formatDate(m.dob), m.relationship, m.medicalRecord];
        drawValue(p2, colStartX + 4, y, vals[c], font, 9);
      }
      colStartX += cols[c].w;
    }
    y -= 22;
  }
  y -= 10;

  // Uninsured contact
  drawCheckItem(p2, M, y, "Yes, I would like Kaiser Permanente to contact me to discuss health care coverage options.", body.contactMe ?? false, font, fontBold);
  y -= 28;

  // Section 3: Patient Agreement
  y = drawSectionHeader(p2, M, y, "Section 3: Patient Agreement", fontBold, CW);
  y -= 4;

  // Credit check opt-out
  drawCheckItem(p2, M, y, "Opt-out: Do not use credit reporting agencies to determine eligibility.", body.optOutCreditCheck ?? false, font, fontBold);
  y -= 24;

  // Declaration text
  const declaration =
    "I hereby declare that all information set forth above in this application is true, accurate, " +
    "and complete in all respects. I also acknowledge and agree that I am liable to KFHP/H for all " +
    "amounts owing to KFHP/H for medical supplies and services that are not eligible under the " +
    'program (the "Remaining Amounts").';

  const declWords = declaration.split(" ");
  let declLine = "";
  for (const word of declWords) {
    const test = declLine ? `${declLine} ${word}` : word;
    if (font.widthOfTextAtSize(test, 8) > CW) {
      p2.drawText(declLine, { x: M, y, size: 8, font, color: NAVY });
      y -= 12;
      declLine = word;
    } else {
      declLine = test;
    }
  }
  if (declLine) {
    p2.drawText(declLine, { x: M, y, size: 8, font, color: NAVY });
    y -= 28;
  }

  // Signature line
  p2.drawLine({ start: { x: M, y }, end: { x: M + CW * 0.6, y }, thickness: 0.5, color: NAVY });
  drawLabel(p2, M, y - 12, "SIGNATURE", font);

  const dateLineX = M + CW * 0.65;
  p2.drawLine({ start: { x: dateLineX, y }, end: { x: W - M, y }, thickness: 0.5, color: NAVY });
  drawLabel(p2, dateLineX, y - 12, "DATE", font);

  const today = new Date();
  const dateStr = `${(today.getMonth() + 1).toString().padStart(2, "0")}/${today.getDate().toString().padStart(2, "0")}/${today.getFullYear()}`;
  drawValue(p2, dateLineX + 4, y + 4, dateStr, font);
  y -= 36;

  // Submission info
  y = drawSectionHeader(p2, M, y, "How to Submit", fontBold, CW);
  y -= 4;
  const submitLines = [
    "Print and sign this application, then submit using one of these methods:",
    "",
    "Fax: 206-877-0640",
    "Mail: Kaiser Permanente MFA Program, PO Box 34584, Seattle, WA 98124-1584",
    "In person: Drop off at any Kaiser Permanente facility",
    "Phone: 1-800-442-4014 (TTY 711), Mon-Fri, 8 a.m. to 5 p.m. PST",
  ];
  for (const line of submitLines) {
    if (line) {
      p2.drawText(line, { x: M + 4, y, size: 8, font: line.includes(":") ? fontBold : font, color: NAVY });
    }
    y -= 12;
  }

  // Footer
  y -= 8;
  p2.drawLine({ start: { x: M, y }, end: { x: W - M, y }, thickness: 0.5, color: LIGHT_GRAY });
  y -= 12;
  p2.drawText("DS-2094 (03-25) WASHINGTON - Generated by Civis Health", { x: M, y, size: 7, font, color: GRAY });

  return pdfDoc.save();
}

async function generateGenericPdf(
  body: { patientName: string; income: number; householdSize: number },
  hospital: Hospital
): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([612, 792]);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const { height } = page.getSize();
  let y = height - 60;

  page.drawText("Financial Assistance Application", {
    x: 50, y, size: 22, font: fontBold, color: NAVY,
  });
  y -= 20;
  page.drawText("Generated by Civis Health", {
    x: 50, y, size: 10, font, color: GRAY,
  });
  y -= 8;
  page.drawLine({
    start: { x: 50, y }, end: { x: 562, y },
    thickness: 1, color: TEAL,
  });
  y -= 40;

  page.drawText("Patient Information", {
    x: 50, y, size: 14, font: fontBold, color: NAVY,
  });
  y -= 28;

  const fields = [
    ["Patient Name", body.patientName],
    ["Hospital", hospital.name],
    ["Program", hospital.policy_name],
    ["Annual Household Income", `$${Number(body.income).toLocaleString()}`],
    ["Household Size", String(body.householdSize)],
    ["Date", new Date().toLocaleDateString("en-US")],
  ];

  for (const [label, value] of fields) {
    page.drawText(`${label}:`, { x: 50, y, size: 11, font: fontBold, color: NAVY });
    page.drawText(value, { x: 220, y, size: 11, font, color: NAVY });
    y -= 24;
  }

  y -= 20;
  page.drawText("Declaration", {
    x: 50, y, size: 14, font: fontBold, color: NAVY,
  });
  y -= 24;
  const declaration =
    "I hereby certify that the information provided above is true and correct to the best of my knowledge. " +
    "I am requesting consideration for financial assistance for medical services received at the above-named hospital.";

  const words = declaration.split(" ");
  let line = "";
  for (const word of words) {
    const testLine = line ? `${line} ${word}` : word;
    if (font.widthOfTextAtSize(testLine, 10) > 490) {
      page.drawText(line, { x: 50, y, size: 10, font, color: NAVY });
      y -= 16;
      line = word;
    } else {
      line = testLine;
    }
  }
  if (line) {
    page.drawText(line, { x: 50, y, size: 10, font, color: NAVY });
    y -= 40;
  }

  page.drawLine({ start: { x: 50, y }, end: { x: 300, y }, thickness: 0.5, color: NAVY });
  page.drawText("Patient Signature", { x: 50, y: y - 14, size: 9, font, color: GRAY });
  page.drawLine({ start: { x: 350, y }, end: { x: 520, y }, thickness: 0.5, color: NAVY });
  page.drawText("Date", { x: 350, y: y - 14, size: 9, font, color: GRAY });

  return pdfDoc.save();
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { hospital_id, patientName } = body;

    if (!patientName || !hospital_id) {
      return NextResponse.json(
        { error: "Missing required fields: patientName, hospital_id" },
        { status: 400 }
      );
    }

    const hospital = hospitals.find((h) => h.hospital_id === hospital_id);
    if (!hospital) {
      return NextResponse.json(
        { error: "Hospital not found" },
        { status: 404 }
      );
    }

    let pdfBytes: Uint8Array;

    if (hospital_id === "kaiser-wa") {
      pdfBytes = await generateKaiserWaPdf(body as KaiserWaBody);
    } else {
      pdfBytes = await generateGenericPdf(body, hospital);
    }

    return new NextResponse(Buffer.from(pdfBytes), {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${hospital_id}-mfa-application.pdf"`,
      },
    });
  } catch (error) {
    console.error("PDF generation error:", error);
    return NextResponse.json(
      { error: "Failed to generate application PDF" },
      { status: 500 }
    );
  }
}
