import { NextRequest, NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { patientName, hospitalName, income, householdSize } = body;

    if (!patientName || !hospitalName || income == null || !householdSize) {
      return NextResponse.json(
        { error: "Missing required fields: patientName, hospitalName, income, householdSize" },
        { status: 400 }
      );
    }

    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([612, 792]); // US Letter
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const navy = rgb(15 / 255, 23 / 255, 42 / 255);
    const gray = rgb(100 / 255, 116 / 255, 139 / 255);

    const { height } = page.getSize();
    let y = height - 60;

    // Header
    page.drawText("Financial Assistance Application", {
      x: 50,
      y,
      size: 22,
      font: fontBold,
      color: navy,
    });
    y -= 20;
    page.drawText("Generated by Civis Health", {
      x: 50,
      y,
      size: 10,
      font,
      color: gray,
    });
    y -= 8;
    page.drawLine({
      start: { x: 50, y },
      end: { x: 562, y },
      thickness: 1,
      color: rgb(212 / 255, 168 / 255, 67 / 255), // gold
    });

    y -= 40;

    // Patient Information section
    page.drawText("Patient Information", {
      x: 50,
      y,
      size: 14,
      font: fontBold,
      color: navy,
    });
    y -= 28;

    const fields = [
      ["Patient Name", patientName],
      ["Hospital", hospitalName],
      ["Annual Household Income", `$${Number(income).toLocaleString()}`],
      ["Household Size", String(householdSize)],
      ["Date", new Date().toLocaleDateString("en-US")],
    ];

    for (const [label, value] of fields) {
      page.drawText(`${label}:`, { x: 50, y, size: 11, font: fontBold, color: navy });
      page.drawText(value, { x: 220, y, size: 11, font, color: navy });
      y -= 24;
    }

    y -= 20;
    page.drawText("Declaration", {
      x: 50,
      y,
      size: 14,
      font: fontBold,
      color: navy,
    });
    y -= 24;
    const declaration =
      "I hereby certify that the information provided above is true and correct to the best of my knowledge. " +
      "I am requesting consideration for financial assistance for medical services received at the above-named hospital.";

    // Simple word-wrap for declaration
    const words = declaration.split(" ");
    let line = "";
    for (const word of words) {
      const testLine = line ? `${line} ${word}` : word;
      if (font.widthOfTextAtSize(testLine, 10) > 490) {
        page.drawText(line, { x: 50, y, size: 10, font, color: navy });
        y -= 16;
        line = word;
      } else {
        line = testLine;
      }
    }
    if (line) {
      page.drawText(line, { x: 50, y, size: 10, font, color: navy });
      y -= 40;
    }

    // Signature lines
    page.drawLine({ start: { x: 50, y }, end: { x: 300, y }, thickness: 0.5, color: navy });
    page.drawText("Patient Signature", { x: 50, y: y - 14, size: 9, font, color: gray });

    page.drawLine({ start: { x: 350, y }, end: { x: 520, y }, thickness: 0.5, color: navy });
    page.drawText("Date", { x: 350, y: y - 14, size: 9, font, color: gray });

    const pdfBytes = await pdfDoc.save();

    return new NextResponse(Buffer.from(pdfBytes), {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="civis-health-application.pdf"`,
      },
    });
  } catch (error) {
    console.error("PDF generation error:", error);
    return NextResponse.json(
      { error: "Failed to generate application PDF" },
      { status: 500 }
    );
  }
}
